### PR TITLE
Apply clippy

### PR DESCRIPTION
**Pull request by justaddcoffee**
@hrshdhgd @caufieldjh @iQuxLE what do you think about this (applying `cargo clippy` in qc.yml?)

I've refactored our existing code to pass `cargo clippy` - this PR would also enforce less strict clippy suggestions

### CODE REVIEW

**Comment by hrshdhgd** [comment]
Is this a result of `cargo clips --fix` ? I like this idea!

**Comment by caufieldjh** [comment]
Clippy does do some nice linting.

I'm in favor of adding it to the QC workflow but can we hold off until the changes in #55 are complete? That PR will make some major changes to that workflow to get coverage working

**Comment by justaddcoffee** [comment]
> I'm in favor of adding it to the QC workflow but can we hold off until the changes in https://github.com/monarch-initiative/semsimian/pull/55 are complete? That PR will make some major changes to that workflow to get coverage working

@caufieldjh yes, definitely - let's merge whatever PRs we have going before we merge this

**Comment by justaddcoffee** [comment]
> Is this a result of cargo clippy --fix ? I like this idea!

yep, clippy is pretty good

**Comment by justaddcoffee** [comment]
@hrshdhgd should we close this in favor of #71 , or are these different

**Comment by hrshdhgd** [comment]
Did you manually refactor anything?

**Comment by justaddcoffee** [comment]
>  Did you manually refactor anything based on chippy's recommendation?

yeah, I think I refactored the closure and IC maps b/c clippy said they were too complicated - this changed a lot of things

**Comment by hrshdhgd** [comment]
Yeah I don't think I did any of that. We could pull down main to this branch and see what changes (?)

**Comment by hrshdhgd** [comment]
I think I messed up while resolving conflicts. The code has changed quite a bit since this branch was originally created. Could we ditch this and create a new branch with updated code @justaddcoffee ? Sorry about this!

**Comment by justaddcoffee** [comment]
@hrshdhgd no problem - this PR is pretty stale

**Comment by hrshdhgd** [comment]
#72 does what you intended to do.

**Pull request closed without merging**
