### PR TITLE
Spring cleaning

### PR DESCRIPTION
**Pull request by justaddcoffee**
Just removing old code - all tests still pass, but could everyone @hrshdhgd @caufieldjh @iQuxLE have a look and make sure I'm not throwing out anything useful?

### CODE REVIEW

**Comment by hrshdhgd** [comment]
Are we deleting all these files? Where is all the code then?

**Comment by justaddcoffee** [comment]
Yep, definitely let me know if I've deleted anything we need!

**Review by caufieldjh — COMMENTED** [review]
Do we have a function for getting MRCAs other than the one in `similarity.rs`?
Do we need one?
Or are we assuming that once we get closures this is trivial?

**Comment by justaddcoffee** [comment]
> Do we have a function for getting MRCAs other than the one in similarity.rs?

I just added back `_mrca_and_score()` - it's not used now and is pretty simple, but for sure we'll need something like this eventually

**Review by caufieldjh — APPROVED** [review]

**Review by hrshdhgd — APPROVED** [review]
Looks good to me

**Review by iQuxLE — COMMENTED** [review]
fine for me

**Pull request merged**
