### PR TITLE
Add all_by_all_pairwise_similarity()

### PR DESCRIPTION
**Pull request by justaddcoffee**
To move all by all comparison from OAK into semsimian (addresses #44)

### CODE REVIEW

**Comment by hrshdhgd** [comment]
@justaddcoffee , since you started the PR I can't ask you for a review. But this is ready to be merged. Please go through this thoroughly. Extra eyes will definitely help.

**Comment by justaddcoffee** [comment]
> @justaddcoffee , since you started the PR I can't ask you for a review. But this is ready to be merged. Please go through this thoroughly. Extra eyes will definitely help.


@hrshdhgd will do! thanks

**Comment by justaddcoffee** [comment]
I had a look and made some comments, and also updated https://github.com/INCATools/ontology-access-kit/pull/579 to align with this

One thing we are missing is the common ancestor information - we will need that for the all x all but we are only sending back jaccard and resnik similarity. 

@hrshdhgd maybe we can merge this and then do another PR to [capture the common ancestor](https://github.com/INCATools/ontology-access-kit/blob/3a91fc67ba8145bb8afe93fade2749e302353383/src/oaklib/implementations/semsimian/semsimian_implementation.py#L144) and also [calculate phenodigm](https://github.com/INCATools/ontology-access-kit/blob/3a91fc67ba8145bb8afe93fade2749e302353383/src/oaklib/implementations/semsimian/semsimian_implementation.py#L148)

**Review by caufieldjh — APPROVED** [review]

**Comment by hrshdhgd** [comment]
> maybe we can merge this and then do another PR to [capture the most informative common ancestor](https://github.com/INCATools/ontology-access-kit/blob/3a91fc67ba8145bb8afe93fade2749e302353383/src/oaklib/implementations/semsimian/semsimian_implementation.py#L144) and also [calculate phenodigm](https://github.com/INCATools/ontology-access-kit/blob/3a91fc67ba8145bb8afe93fade2749e302353383/src/oaklib/implementations/semsimian/semsimian_implementation.py#L148) on the rust side?

Follow up PR: https://github.com/monarch-initiative/semsimian/pull/61

**Pull request merged**
