### PR TITLE
Trying to allow threads to access self simultaneously

### PR DESCRIPTION
**Pull request by justaddcoffee**
Experimenting with rwlock instead of mutex to allow threads to access self simulaneously. Currently (if I understand correctly) `self` is locked by each thread when it computes a similarity score, which possibly prevents `rayon` from paralleizing efficiently

### CODE REVIEW

**Comment by justaddcoffee** [comment]
@hrshdhgd have a look at this - this PR seems to use all 10 cores on my mac when doing an all x all 

(There are two tests failing so this PR is not nearly finished though)

**Comment by justaddcoffee** [comment]
@caufieldjh I just noticed though that HP all versus all now completed in 12h on my laptop

**Comment by caufieldjh** [comment]
OK, that's very promising!

**Comment by justaddcoffee** [comment]
@hrshdhgd could we add an `indicatif` progress bar to the all x all comparison? 

Also, I get this error when I run this on the Oak side in [this PR](https://github.com/INCATools/ontology-access-kit/pull/579) - not sure what the problem is, maybe could use a Python test in semsimian to test this?

```
(rustsim) ~/PythonProject/ontology-access-kit implement_all_by_all_in_semsimian $ time runoak --stacktrace -i semsimian:sqlite:obo:bfo similarity -p hp .all @ .all > /dev/null 
[00:00:00] Building closure and IC map: ████████████████████████████████████████ 100%thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/lib.rs:57:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/jtr4v/anaconda3/envs/rustsim/bin/runoak", line 6, in <module>
    sys.exit(main())
  File "/Users/jtr4v/anaconda3/envs/rustsim/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jtr4v/anaconda3/envs/rustsim/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jtr4v/anaconda3/envs/rustsim/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jtr4v/anaconda3/envs/rustsim/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jtr4v/anaconda3/envs/rustsim/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jtr4v/PythonProject/ontology-access-kit/src/oaklib/cli.py", line 2746, in similarity
    for sim in impl.all_by_all_pairwise_similarity(
  File "/Users/jtr4v/PythonProject/ontology-access-kit/src/oaklib/implementations/semsimian/semsimian_implementation.py", line 135, in all_by_all_pairwise_similarity
    all_results = self.semsimian.all_by_all_pairwise_similarity(
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value

real    0m2.905s
user    0m2.360s
sys     0m2.205s
```

**Comment by hrshdhgd** [comment]
I ran it on the `oaklib` side and this is what I found:

```
predicates=["hp"]
subjects = ['BFO:0000001', 'BFO:0000002', 'BFO:0000003', 'BFO:0000004', 'BFO:0000006', 'BFO:0000008', 'BFO:0000009', 'BFO:0000011', 'BFO:0000015', 'BFO:0000016', 'BFO:0000017', 'BFO:0000018', 'BFO:0000019', 'BFO:0000020', 'BFO:0000023', 'BFO:0000024', 'BFO:0000026', 'BFO:0000027', 'BFO:0000028', 'BFO:0000029', 'BFO:0000030', 'BFO:0000031', 'BFO:0000034', 'BFO:0000035', 'BFO:0000038', 'BFO:0000040', 'BFO:0000140', 'BFO:0000141', 'BFO:0000142', 'BFO:0000144', 'BFO:0000145', 'BFO:0000146', 'BFO:0000147', 'BFO:0000148', 'BFO:0000179', 'BFO:0000180', 'BFO:0000182', 'IAO:0000111', 'IAO:0000112', 'IAO:0000115', 'IAO:0000116', 'IAO:0000117', 'IAO:0000118', 'IAO:0000119', 'IAO:0000232', 'IAO:0000412', 'IAO:0000600', 'IAO:0000601', 'IAO:0000602', 'IAO:0010000', 'dce:contributor', 'dce:member', 'dcterms:license', 'foaf:homepage', 'foaf:mbox', 'obo:bfo.owl', 'rdfs:isDefinedBy', 'rdfs:seeAlso']

objects = ['BFO:0000001', 'BFO:0000002', 'BFO:0000003', 'BFO:0000004', 'BFO:0000006', 'BFO:0000008', 'BFO:0000009', 'BFO:0000011', 'BFO:0000015', 'BFO:0000016', 'BFO:0000017', 'BFO:0000018', 'BFO:0000019', 'BFO:0000020', 'BFO:0000023', 'BFO:0000024', 'BFO:0000026', 'BFO:0000027', 'BFO:0000028', 'BFO:0000029', 'BFO:0000030', 'BFO:0000031', 'BFO:0000034', 'BFO:0000035', 'BFO:0000038', 'BFO:0000040', 'BFO:0000140', 'BFO:0000141', 'BFO:0000142', 'BFO:0000144', 'BFO:0000145', 'BFO:0000146', 'BFO:0000147', 'BFO:0000148', 'BFO:0000179', 'BFO:0000180', 'BFO:0000182', 'IAO:0000111', 'IAO:0000112', 'IAO:0000115', 'IAO:0000116', 'IAO:0000117', 'IAO:0000118', 'IAO:0000119', 'IAO:0000232', 'IAO:0000412', 'IAO:0000600', 'IAO:0000601', 'IAO:0000602', 'IAO:0010000', 'dce:contributor', 'dce:member', 'dcterms:license', 'foaf:homepage', 'foaf:mbox', 'obo:bfo.owl', 'rdfs:isDefinedBy', 'rdfs:seeAlso']
```

Is this what we expect to pass?

**Comment by hrshdhgd** [comment]
@justaddcoffee 
```
time runoak --stacktrace -vvv -i semsimian:sqlite:obo:bfo similarity -p i,p .all @ .all
```

completes in 6 seconds.

**Comment by caufieldjh** [comment]
Fantastic!

**Comment by hrshdhgd** [comment]
> @hrshdhgd could we add an `indicatif` progress bar to the all x all comparison?


Done!

**Comment by justaddcoffee** [comment]
> -p i,p is what we need. hp was being passed.

Ah okay! I was calling it with 'hp' as a predicate argument for some weird reason (I was running this using my command history) 

Still, seems like we should catch this panic (presumably caused when the user specifies `-p [some predicate that doesn't exist]`

**Comment by justaddcoffee** [comment]
@hrshdhgd looks like this python test is failing in this branch too (possibly not just in this branch?)

```
$ pytest python/tests/test_python.py 

    def test_resnik_similarity(self):
        term1 = "apple"
        term2 = "banana"
        predicates = {"related_to"}
        result = self.semsimian.resnik_similarity(term1, term2, predicates)
>       self.assertEqual(result, ({"banana"}, 1.3219280948873622))
E       AssertionError: Tuples differ: ({'banana'}, 2.0) != ({'banana'}, 1.3219280948873622)
E       
E       First differing element 1:
E       2.0
E       1.3219280948873622
E       
E       - ({'banana'}, 2.0)
E       + ({'banana'}, 1.3219280948873622)
```

**Comment by hrshdhgd** [comment]
Did you run `maturin develop` locally first before `pytest`?

**Review by caufieldjh — APPROVED** [review]

**Comment by caufieldjh** [comment]
Is this mergeable now?

**Comment by hrshdhgd** [comment]
I'm going write a note about the calculation real quick and then we can merge + release?

**Pull request merged**
