### PR TITLE
Experimenting with writing results in `semsimian` itself

### LINKED ISSUE #74: Add method `semsimian embedding-similarity` to semsimian
We should implement a method for computing a semantic similarity profile from an embedding.

Input:

- `--embedding` (a TSV file where the first column is an identifiers, and all subsequent columns describe the embedding (numbers)).
- `--similarity-measure` (or whatever semsimian calls this), default `cosine`.
- the options for streaming writing etc, see #73 
- the usual options for selecting terms

Output:

A semantic similarity profile according to the oak-semsim standard (slightly reduced, as there is no IC or anything computed).

@caufieldjh can you link to an example embedding (does not matter about what).

@hrshdhgd can you take this on?

### PR DESCRIPTION
**Pull request by hrshdhgd**
This PR is an experimentation of writing the result as follows:

| subject_id | object_id | jaccard_similarity      | ancestor_information_content | phenodigm_score        | cosine_similarity       | ancestor_id |
|------------|-----------|-------------------------|-----------------------------|------------------------|-------------------------|-------------|
| banana     | apple     | 0.3333333333333333      | 1.3219280948873622          | 0.6638092333613531     | -0.0811959702204112     | banana      |
| apple      | apple     | 1                       | 2.321928094887362           | 1.523787417879332      | 1                       | apple       |

Fixes #74

### CODE REVIEW

**Review by hrshdhgd — COMMENTED** [review]
@justaddcoffee , @caufieldjh : Does this code make sense for calculating `cosine` similarity between embeddings of 2 nodes? Or am I completely mistaken?

EDIT: [Here's the commit](https://github.com/monarch-initiative/semsimian/pull/73/commits/d1ec6bf4331efff6176043737b77320a66da8560).

**Comment by caufieldjh** [comment]
I believe that's correct - may be helpful to try it out with negative values too

**Review by caufieldjh — APPROVED** [review]
Great stuff! I do have this nagging feeling that the list of column_names in `all_by_all_pairwise_similarity_with_output` should be defined elsewhere (e.g., retrieved from the OAK data model) for future-proofing sake and because other projects depend on having the same set of metrics, but this covers all of our current use cases and then some

**Review by justaddcoffee — APPROVED** [review]
Looks good

If need be I think I see some spots where we maybe could speed this up in the future, but this likely is fast enough

**Comment by hrshdhgd** [comment]
>If need be I think I see some spots where we maybe could speed this up in the future

Hey @justaddcoffee ! Could you point out those improvements? If these are straightforward enough, I could include them in this PR (?)

**Comment by justaddcoffee** [comment]
> Hey @justaddcoffee ! Could you please point out those improvements? If these are straightforward enough, I could include them in this PR (?)

actually I see you are using `par_iter` [here](https://github.com/monarch-initiative/semsimian/blob/8442692bb244a8e65e586fd89bc2bbe24d4cd0f6/src/lib.rs#L215) so I think this is as fast as what I had in mind - nevermind!

**Comment by hrshdhgd** [comment]
> 

This was exactly what I was thinking. Another alternative is make the `column_names` an attribute (`output_features`) of the `RustSemsimian` class
```
impl RustSemsimian {
    pub fn new(spo: Vec<(TermID, Predicate, TermID)>, output_features:Vec<String>) -> RustSemsimian {
        RustSemsimian {
            spo,
            output_features,
            ic_map: HashMap::new(),
            closure_map: HashMap::new(),
            embeddings: Vec::new(),
        }
    }
}
```

This way the param list is not growing as we add features and `RustSemsimian can have all needed information from `oaklib` within itself as attributes. 

Thoughts?

**Comment by caufieldjh** [comment]
I like that - it makes for a more tidy main class and would allow for adding new args as needed.

**Pull request merged**
