### PR TITLE
update release action

### LINKED ISSUE #65: Release action publishes prereleases
Prelease versions don't need to get published to Pypi - the corresponding GH action (https://github.com/monarch-initiative/semsimian/blob/main/.github/workflows/release.yml) can be configured as per https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

### PR DESCRIPTION
**Pull request by glass-ships**
Closes #65 
- only run release action on publish,
- check that publish is not prerelease before building/uploading/publishing

### CODE REVIEW

**Comment by cmungall** [comment]
what's the status of this?

**Comment by glass-ships** [comment]
oh thanks for the reminder!
it should be good to go, I just wasn't able to request a review and forgot to ask about it in slack

**Comment by caufieldjh** [comment]
Why does this replace the LICENSE?

**Comment by glass-ships** [comment]
> Why does this replace the LICENSE?

that's just from merging main into it (I only did it the once though)

**Comment by glass-ships** [comment]
Going to close this PR and re-open one, because on second look, you're right, there's no reason for the dockerfile to be deleted / license to be changed like it is.

**Pull request closed without merging**
